dist: xenial

language: python
python:
  - "3.7"
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Create environment and use conda to install packages and their dependencies
  - conda env create -q --file environment.yml
  - conda activate rivgraph
  - conda uninstall rivgraph
  - pip install pytest
# command to run tests
script:
  - python setup.py install
  - pytest
  - pytest --cov-config=.coveragerc --cov=rivgraph/

jobs:
  include:
    - stage: coverage
      python: "3.7"
      install:
        - sudo apt-get update
        # We do this conditionally because it saves us some downloading if the
        # version is the same.
        - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
          else
            wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
          fi
        - bash miniconda.sh -b -p $HOME/miniconda
        - source "$HOME/miniconda/etc/profile.d/conda.sh"
        - hash -r
        - conda config --set always_yes yes --set changeps1 no
        - conda update -q conda
        # Useful for debugging any issues with conda
        - conda info -a

        # Create environment and use conda to install packages and their dependencies
        - conda env create -q --file environment.yml
        - conda activate rivgraph
        - conda uninstall rivgraph
        - pip install pytest pytest-cov coveralls
      script:
        - pytest --cov-config=.coveragerc --cov=rivgraph/
      after_success:
        - coveralls
