name: rivgraph
channels:
  - jschwenk
  - conda-forge
  - defaults
dependencies:
<<<<<<< HEAD
  - python=3.6
  - gdal
  - numpy
=======
  - rivgraph
>>>>>>> f9d98afbc425542e0c99f39a0009876ee03313c6
  - geopandas=0.7.0
  - scikit-image
  - opencv
  - networkx
  - matplotlib
<<<<<<< HEAD
  - pyproj
  - Shapely
  - Fiona
=======
>>>>>>> f9d98afbc425542e0c99f39a0009876ee03313c6
